---
# tasks file for vector-role
- name: Get Vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/0.32.1/vector-0.32.1-1.x86_64.rpm"
    dest: "./vector.rpm"

- name: Install Vector
  ansible.builtin.yum:
    name: "vector"
    state: present
  notify: Start Vector service

- name: Create Vector configuration file
  template:
    src: vector_config.j2
    dest: /home/devops/vector
  become: yes
  become_user: devops
  notify: Restart Vector service
